// Golden-master + behavioral parity for rate-assignment (task 5.4/5.5):
//
// - addBlocks: EXACT parity against R on the frozen simple1/imperial fixture
//   design (fixtures/simple1/imperial/seed/trial-design.geojson + a reference
//   blocks.json generated by tools/gen-blocks-fixture.R, replaying the same
//   pipeline with set.seed(20260702) and calling add_blocks()). The TS side
//   parses rates straight out of the frozen GeoJSON — it does not re-run
//   assignRates, so this test is only about addBlocks's own logic.
// - changeRates: built from the same fixture design; asserts targeted plots
//   changed and everything else stayed untouched, across all three rateBy
//   modes.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { Feature, FeatureCollection } from "geojson";
import { addBlocks, changeRates } from "../src/rate-assignment.js";
import type { InputDesign, PlotInfo, RateInfo, TrialDesign } from "../src/types.js";

const ROOT = join(import.meta.dirname, "..");

function load<T>(relPath: string): T {
  return JSON.parse(readFileSync(join(ROOT, relPath), "utf8")) as T;
}

interface FixtureRow {
  strip_id: number | null;
  plot_id: number | null;
  type: string;
  block_id: number | null;
  plot_id_within_block: number | null;
}

/** Builds a one-input TrialDesign straight from a frozen trial-design.geojson. */
function trialDesignFromFixture(): TrialDesign {
  const geojson = load<FeatureCollection>("fixtures/simple1/imperial/seed/trial-design.geojson");
  const plotInfo = load<PlotInfo[][]>("fixtures/simple1/imperial/plot-info.json")[0]![0]!;
  const rateInfo = load<RateInfo[][]>("fixtures/simple1/imperial/rate-info.json")[0]![0]!;

  const plots: Feature[] = [];
  const headlands: Feature[] = [];
  for (const f of geojson.features) {
    const type = (f.properties as { type: string }).type;
    (type === "headland" ? headlands : plots).push(f);
  }

  const input: InputDesign = {
    plotInfo,
    rateInfo,
    plots: { type: "FeatureCollection", features: plots },
    headlands: { type: "FeatureCollection", features: headlands },
    abLine: { type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: [] } },
    guidanceLines: { type: "FeatureCollection", features: [] },
  };
  return { inputs: [input], seed: 20260702 };
}

describe("addBlocks parity with R (task 5.4)", () => {
  it("matches R's block_id and plot_id_within_block exactly on the frozen fixture", () => {
    const td = trialDesignFromFixture();
    const reference = load<FixtureRow[]>("fixtures/simple1/imperial/seed/blocks.json");

    const result = addBlocks(td);
    const input = result.inputs[0]!;

    const actualByKey = new Map<string, { blockId: number; plotIdWithinBlock: number }>();
    for (const f of input.plots.features) {
      const p = f.properties as { strip_id: number; plot_id: number; block_id: number; plot_id_within_block: number };
      actualByKey.set(`${p.strip_id}:${p.plot_id}`, { blockId: p.block_id, plotIdWithinBlock: p.plot_id_within_block });
    }

    let matched = 0;
    for (const row of reference) {
      if (row.type === "headland") continue;
      const actual = actualByKey.get(`${row.strip_id}:${row.plot_id}`);
      expect(actual, `plot ${row.strip_id}:${row.plot_id} missing from TS output`).toBeDefined();
      expect(actual!.blockId).toBe(row.block_id);
      expect(actual!.plotIdWithinBlock).toBe(row.plot_id_within_block);
      matched += 1;
    }

    expect(matched).toBe(reference.filter((r) => r.type !== "headland").length);
    expect(matched).toBeGreaterThan(0);
  });

  it("sets block_id and plot_id_within_block to null on headland plots (R: NA)", () => {
    const td = trialDesignFromFixture();
    const result = addBlocks(td);
    const headlandProps = result.inputs[0]!.headlands.features.map(
      (f) => f.properties as { block_id: number | null; plot_id_within_block: number | null },
    );
    expect(headlandProps.length).toBeGreaterThan(0);
    for (const p of headlandProps) {
      expect(p.block_id).toBeNull();
      expect(p.plot_id_within_block).toBeNull();
    }
  });
});

describe("changeRates (task 5.5)", () => {
  function rateByKey(td: TrialDesign): Map<string, number> {
    const map = new Map<string, number>();
    for (const f of td.inputs[0]!.plots.features) {
      const p = f.properties as { strip_id: number; plot_id: number; rate: number };
      map.set(`${p.strip_id}:${p.plot_id}`, p.rate);
    }
    return map;
  }

  it("rateBy strip: changes only the targeted strips", () => {
    const td = trialDesignFromFixture();
    const before = rateByKey(td);

    const result = changeRates(td, { stripIds: [3, 7], newRates: [150, 90], rateBy: "strip" });
    const after = rateByKey(result);

    for (const [key, rate] of after) {
      const [stripId] = key.split(":").map(Number);
      if (stripId === 3) expect(rate).toBe(150);
      else if (stripId === 7) expect(rate).toBe(90);
      else expect(rate).toBe(before.get(key));
    }
  });

  it('rateBy "all": changes only the targeted plot positions within the targeted strips', () => {
    const td = trialDesignFromFixture();
    const before = rateByKey(td);

    const result = changeRates(td, { stripIds: [2, 4], plotIds: [1, 2, 3], newRates: [0], rateBy: "all" });
    const after = rateByKey(result);

    for (const [key, rate] of after) {
      const [stripId, plotId] = key.split(":").map(Number);
      if ((stripId === 2 || stripId === 4) && plotId! >= 1 && plotId! <= 3) {
        expect(rate).toBe(0);
      } else {
        expect(rate).toBe(before.get(key));
      }
    }
  });

  it('rateBy "plot": applies the plotIds x stripIds matrix, matrix row = plot position, column = strip', () => {
    const td = trialDesignFromFixture();
    const before = rateByKey(td);

    const result = changeRates(td, {
      stripIds: [2, 4],
      plotIds: [5, 7],
      newRates: [
        [100, 110],
        [200, 210],
      ],
      rateBy: "plot",
    });
    const after = rateByKey(result);

    expect(after.get("2:5")).toBe(100);
    expect(after.get("4:5")).toBe(110);
    expect(after.get("2:7")).toBe(200);
    expect(after.get("4:7")).toBe(210);

    for (const [key, rate] of after) {
      if (["2:5", "4:5", "2:7", "4:7"].includes(key)) continue;
      expect(rate).toBe(before.get(key));
    }
  });

  it("throws when inputName is missing on a multi-input design", () => {
    const td = trialDesignFromFixture();
    const twoInput: TrialDesign = { inputs: [td.inputs[0]!, td.inputs[0]!], seed: td.seed };
    expect(() => changeRates(twoInput, { stripIds: [1], newRates: 100 })).toThrow(
      /specify which input/,
    );
  });

  it("throws on an unknown strip id", () => {
    const td = trialDesignFromFixture();
    expect(() => changeRates(td, { stripIds: [9999], newRates: 100 })).toThrow(/Strip id/);
  });

  it("throws on newRates/stripIds length mismatch for rateBy strip", () => {
    const td = trialDesignFromFixture();
    expect(() => changeRates(td, { stripIds: [1, 2], newRates: [100], rateBy: "strip" })).toThrow(
      /same length as stripIds/,
    );
  });
});
